version: '2'
services:
  web:
     image: php:apache
     depends_on:
        - api
     environment:
        - USERNAME=toto
        - PASSWORD=python
     volumes:
        - ./website:/var/www/html
     ports:
        - "8082:80"
     networks:
        - api-pozos
  api:
     image: api-pozos:1
     ports:
        - "4000:5000"
     volumes:
        - ./simple-api/student_age.json:/data/student_age.json
     networks:
        - api-pozos
networks:
   api-pozos:
  
     
